### ISSUE TITLE
Add an iOS version

### ISSUE THREAD

**Issue by melkir** [RioBus/ionic-app#61]
Hello,
I can't launch your application on iOS, I would to test if it's also work on it but I'm stuck on the launch screen with the logo :(

**Comment by fmsouza** [comment]
Hi @melkir! Until now, this app is focused only in Android, because it has a running native iOS version in https://github.com/RioBus/ios

As we are not needing iOS support right now, we did not tested in iOS devices, so we don't know wether it runs or not yet. But if you want, we would be glad to accept your pull request making sure it works for both Android and iOS.
